"""03052025active

Revision ID: 006c5ab0305b
Revises: f12b639d8751
Create Date: 2025-05-03 13:56:48.871984

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '006c5ab0305b'
down_revision: Union[str, None] = 'f12b639d8751'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('authors', sa.Column('biography', sa.String(length=1000), nullable=True))
    op.add_column('users', sa.Column('biography', sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'biography')
    op.drop_column('authors', 'biography')
    # ### end Alembic commands ###
