"""13062025_2

Revision ID: 1082db555fde
Revises: 296b45f6c49b
Create Date: 2025-06-13 22:03:44.634288

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1082db555fde'
down_revision: Union[str, None] = '296b45f6c49b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('cart_items_id_book_fkey', 'cart_items', type_='foreignkey')
    op.drop_constraint('cart_items_id_cart_fkey', 'cart_items', type_='foreignkey')
    op.create_foreign_key(None, 'cart_items', 'carts', ['id_cart'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'cart_items', 'books', ['id_book'], ['id'], ondelete='CASCADE')
    op.drop_constraint('carts_id_user_fkey', 'carts', type_='foreignkey')
    op.create_foreign_key(None, 'carts', 'users', ['id_user'], ['id'], ondelete='CASCADE')
    op.drop_constraint('comments_id_user_fkey', 'comments', type_='foreignkey')
    op.drop_constraint('comments_id_book_fkey', 'comments', type_='foreignkey')
    op.create_foreign_key(None, 'comments', 'users', ['id_user'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'comments', 'books', ['id_book'], ['id'], ondelete='CASCADE')
    op.drop_constraint('group_books_book_id_fkey', 'group_books', type_='foreignkey')
    op.drop_constraint('group_books_group_id_fkey', 'group_books', type_='foreignkey')
    op.create_foreign_key(None, 'group_books', 'groups', ['group_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'group_books', 'books', ['book_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('purchase_history_user_id_fkey', 'purchase_history', type_='foreignkey')
    op.drop_constraint('purchase_history_book_id_fkey', 'purchase_history', type_='foreignkey')
    op.create_foreign_key(None, 'purchase_history', 'books', ['book_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'purchase_history', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('ratings_id_user_fkey', 'ratings', type_='foreignkey')
    op.drop_constraint('ratings_id_book_fkey', 'ratings', type_='foreignkey')
    op.create_foreign_key(None, 'ratings', 'books', ['id_book'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'ratings', 'users', ['id_user'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ratings', type_='foreignkey')
    op.drop_constraint(None, 'ratings', type_='foreignkey')
    op.create_foreign_key('ratings_id_book_fkey', 'ratings', 'books', ['id_book'], ['id'])
    op.create_foreign_key('ratings_id_user_fkey', 'ratings', 'users', ['id_user'], ['id'])
    op.drop_constraint(None, 'purchase_history', type_='foreignkey')
    op.drop_constraint(None, 'purchase_history', type_='foreignkey')
    op.create_foreign_key('purchase_history_book_id_fkey', 'purchase_history', 'books', ['book_id'], ['id'])
    op.create_foreign_key('purchase_history_user_id_fkey', 'purchase_history', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'group_books', type_='foreignkey')
    op.drop_constraint(None, 'group_books', type_='foreignkey')
    op.create_foreign_key('group_books_group_id_fkey', 'group_books', 'groups', ['group_id'], ['id'])
    op.create_foreign_key('group_books_book_id_fkey', 'group_books', 'books', ['book_id'], ['id'])
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.create_foreign_key('comments_id_book_fkey', 'comments', 'books', ['id_book'], ['id'])
    op.create_foreign_key('comments_id_user_fkey', 'comments', 'users', ['id_user'], ['id'])
    op.drop_constraint(None, 'carts', type_='foreignkey')
    op.create_foreign_key('carts_id_user_fkey', 'carts', 'users', ['id_user'], ['id'])
    op.drop_constraint(None, 'cart_items', type_='foreignkey')
    op.drop_constraint(None, 'cart_items', type_='foreignkey')
    op.create_foreign_key('cart_items_id_cart_fkey', 'cart_items', 'carts', ['id_cart'], ['id'])
    op.create_foreign_key('cart_items_id_book_fkey', 'cart_items', 'books', ['id_book'], ['id'])
    # ### end Alembic commands ###
