"""05052025

Revision ID: 161bdcc6b0b9
Revises: 2873cc793055
Create Date: 2025-05-05 12:24:33.503978

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '161bdcc6b0b9'
down_revision: Union[str, None] = '2873cc793055'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('content', postgresql.BYTEA(), nullable=True))
    op.create_unique_constraint(None, 'books', ['content'])
    op.drop_column('books', 'id_single_book')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('id_single_book', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'books', type_='unique')
    op.drop_column('books', 'content')
    # ### end Alembic commands ###
