"""05052025

Revision ID: 2873cc793055
Revises: 006c5ab0305b
Create Date: 2025-05-05 12:10:42.111725

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2873cc793055'
down_revision: Union[str, None] = '006c5ab0305b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('single_books')
    op.add_column('books', sa.Column('content', postgresql.BYTEA(), nullable=True))
    op.create_unique_constraint(None, 'books', ['content'])
    op.drop_constraint('books_id_single_book_fkey', 'books', type_='foreignkey')
    op.drop_column('books', 'id_single_book')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('id_single_book', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('books_id_single_book_fkey', 'books', 'single_books', ['id_single_book'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_constraint(None, 'books', type_='unique')
    op.drop_column('books', 'content')
    op.create_table('single_books',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('content', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='single_books_pkey'),
    sa.UniqueConstraint('content', name='single_books_content_key')
    )
    # ### end Alembic commands ###
