"""14052025

Revision ID: 296b45f6c49b
Revises: 51b411d31da0
Create Date: 2025-06-13 21:41:53.954473

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '296b45f6c49b'
down_revision: Union[str, None] = '51b411d31da0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('books_genres_id_genre_fkey', 'books_genres', type_='foreignkey')
    op.drop_constraint('books_genres_id_book_fkey', 'books_genres', type_='foreignkey')
    op.create_foreign_key(None, 'books_genres', 'books', ['id_book'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'books_genres', 'genres', ['id_genre'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'books_genres', type_='foreignkey')
    op.drop_constraint(None, 'books_genres', type_='foreignkey')
    op.create_foreign_key('books_genres_id_book_fkey', 'books_genres', 'books', ['id_book'], ['id'])
    op.create_foreign_key('books_genres_id_genre_fkey', 'books_genres', 'genres', ['id_genre'], ['id'])
    # ### end Alembic commands ###
