"""07052025_8

Revision ID: 4b1013fe3b27
Revises: 72a4e35160ff
Create Date: 2025-05-07 09:44:09.384093

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b1013fe3b27'
down_revision: Union[str, None] = '72a4e35160ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('books', 'id_author',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('users', sa.Column('name', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'name')
    op.alter_column('books', 'id_author',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
