"""05062026

Revision ID: 51b411d31da0
Revises: 9769053f7394
Create Date: 2025-06-05 14:16:42.347066

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51b411d31da0'
down_revision: Union[str, None] = '9769053f7394'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group_books',
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.PrimaryKeyConstraint('group_id', 'book_id')
    )
    op.add_column('groups', sa.Column('description', sa.Text(), nullable=True))
    op.drop_constraint('groups_id_book_fkey', 'groups', type_='foreignkey')
    op.drop_column('groups', 'id_book')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('id_book', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('groups_id_book_fkey', 'groups', 'books', ['id_book'], ['id'])
    op.drop_column('groups', 'description')
    op.drop_table('group_books')
    # ### end Alembic commands ###
