"""07052025_6

Revision ID: 5f5ea649b6de
Revises: a72529f03daa
Create Date: 2025-05-07 09:26:31.967167

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f5ea649b6de'
down_revision: Union[str, None] = 'a72529f03daa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('uploaded_by_user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'books', 'users', ['uploaded_by_user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'books', type_='foreignkey')
    op.drop_column('books', 'uploaded_by_user_id')
    # ### end Alembic commands ###
