"""07052025_9

Revision ID: 64af5dea492d
Revises: 001041f1965e
Create Date: 2025-05-07 09:45:11.499578

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64af5dea492d'
down_revision: Union[str, None] = '001041f1965e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('books', 'uploaded_by_user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('books', 'uploaded_by_user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
