"""07052025_7

Revision ID: 72a4e35160ff
Revises: 5f5ea649b6de
Create Date: 2025-05-07 09:42:45.446705

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72a4e35160ff'
down_revision: Union[str, None] = '5f5ea649b6de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('books', 'id_author',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('books', 'uploaded_by_user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('users', sa.Column('name', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'name')
    op.alter_column('books', 'uploaded_by_user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('books', 'id_author',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
