"""Add purchase history table

Revision ID: 9769053f7394
Revises: 64af5dea492d
Create Date: 2025-05-27 12:02:45.552240

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9769053f7394'
down_revision: Union[str, None] = '64af5dea492d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('purchase_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('purchase_date', sa.DateTime(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('books', 'uploaded_by_user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('ratings', 'rating',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ratings', 'rating',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('books', 'uploaded_by_user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_table('purchase_history')
    # ### end Alembic commands ###
